# Generated by Django 3.1.6 on 2021-02-12 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='offices',
            fields=[
                ('officecode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('addressline1', models.CharField(max_length=50)),
                ('addressline2', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('postalcode', models.CharField(max_length=15)),
                ('territory', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='productline',
            fields=[
                ('productline', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('textdescription', models.TextField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('productcode', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('productname', models.CharField(max_length=70)),
                ('productscale', models.CharField(max_length=10)),
                ('productvendor', models.CharField(max_length=50)),
                ('produdescription', models.TextField(max_length=5000)),
                ('quantity_instock', models.SmallIntegerField(max_length=6)),
                ('buyprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('msrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.productline')),
            ],
        ),
    ]
