# Generated by Django 3.1.6 on 2021-02-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_auto_20210211_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offices',
            name='addressline2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='offices',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
