# Generated by Django 3.1.6 on 2021-02-12 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_auto_20210211_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('employeenumber', models.IntegerField(primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('extension', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('jobtitle', models.CharField(max_length=50)),
                ('officecode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.offices')),
                ('reports_to', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.employees')),
            ],
        ),
    ]
