# Generated by Django 3.1.6 on 2021-02-12 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='reports_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.employees'),
        ),
    ]
