# Generated by Django 3.1.6 on 2021-02-12 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0006_auto_20210211_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('custmorenumber', models.IntegerField(primary_key=True, serialize=False)),
                ('customername', models.CharField(max_length=50)),
                ('contact_lastname', models.CharField(max_length=50)),
                ('contact_firstname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('addressline1', models.CharField(max_length=50)),
                ('addressline2', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50, null=True)),
                ('postalcode', models.CharField(max_length=15, null=True)),
                ('country', models.CharField(max_length=50)),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sales_rep_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.employees')),
            ],
        ),
    ]
