# Generated by Django 3.1.6 on 2021-02-12 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='payments',
            fields=[
                ('checknumber', models.CharField(max_length=58, primary_key=True, serialize=False)),
                ('paymentdate', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customernumber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='office.customers')),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('ordernumber', models.IntegerField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('required_date', models.DateField()),
                ('shippeddate', models.DateField()),
                ('status', models.CharField(max_length=15)),
                ('comments', models.TextField(max_length=8000)),
                ('custmomer_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.customers')),
            ],
        ),
    ]
