# Generated by Django 3.1.6 on 2021-02-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0008_orderdetails_orders_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='comments',
            field=models.TextField(max_length=8000, null=True),
        ),
    ]
