# Generated by Django 3.1.6 on 2021-02-12 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0009_auto_20210211_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='custmomer_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.customers'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shippeddate',
            field=models.DateField(null=True),
        ),
    ]
