# Generated by Django 3.1.6 on 2021-02-12 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0011_orderdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='ordernumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.orders'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='productcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.product'),
        ),
    ]
