# Generated by Django 3.1.6 on 2021-02-20 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0013_auto_20210211_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='salary',
            field=models.BigIntegerField(default=100000),
        ),
    ]
